### PR TITLE
Add wallet address search

### PR DESCRIPTION
**Pull request by charlycrs**
Added new method for looking up wallet by address and its test case.

### CODE REVIEW

**Review by chochos — APPROVED** [review]
Need to bump versions before merge

**Comment by charlycrs** [comment]
> Need to bump versions before merge

Jus bumped it, I looked and the last commits were tagged as 0.0.7 but we use 0.0.6 and it was snapshot, so I'm not quite sure

**Review by kushal256 — COMMENTED** [review]
Using https://jitpack.io/#bitsoex/bitso-bitgo-java-api so after merging, make a new github release, and then jitpack will pick it up

**Comment by charlycrs** [comment]
> Using https://jitpack.io/#bitsoex/bitso-bitgo-java-api so after merging, make a new github release, and then jitpack will pick it up

Ah ok, I see that jitpack is 0.0.7, so 0.0.8 is . ok? and then if I merge to master jitpack the release is auto made and jitpack takes it???

**Comment by kushal256** [comment]
Yes, that should do it

**Pull request merged**
